/* Contoso Azure Migrate lab — scenario data */
const LAB = {
  title: "AZ-MIG-201 · Migrate a VMware VM to Azure",
  subtitle: "End-to-end Azure Migrate lab: project, appliance, discovery, assessment, cutover",
  duration: "90–120 minutes",
  level: "Intermediate",
  exam: "AZ-104 · AZ-305 · AZ-801",
  company: "Contoso Ltd.",
  creds: {
    azureUser: "admin@contoso.com",
    azurePass: "Contoso@Azure2026",
    tenant: "contoso.onmicrosoft.com",
    subscription: "Contoso-Prod (8f2a1c44-9b10-4d77-ae31-0c9e4f6b21a8)",
    subId: "8f2a1c44-9b10-4d77-ae31-0c9e4f6b21a8",
    vcenter: "vcenter.contoso.local",
    vcenterIp: "10.10.1.10",
    vcenterUser: "migrate-svc@vsphere.local",
    vcenterPass: "VMware@123",
    applianceAdmin: "Administrator",
    appliancePass: "Applianc3!",
    applianceIp: "10.10.1.50",
    applianceHost: "AzureMigrateAppl",
    guestWinUser: "contoso\\svc-migrate",
    guestWinPass: "Guest@Win2026",
    guestLinUser: "azmigrate",
    guestLinPass: "Guest@Lin2026",
    projectName: "contoso-vmware-migrate",
    rgName: "rg-migrate-prod",
    geography: "Asia",
    targetRegion: "East US",
    applianceName: "contosoappl01",
  },
  expectedKeyPrefix: "CONTOSOAPPL01",
};

const INVENTORY = [
  {
    id: "web01",
    name: "WEB-01",
    os: "Windows Server 2022 Datacenter",
    power: "Powered On",
    cpu: 4,
    mem: 16,
    disks: "OS 80 GB",
    ip: "10.10.20.11",
    tools: "VMware Tools 12.3 (Running)",
    host: "esxi-prod-01.contoso.local",
    cluster: "Prod-Cluster",
    apps: "IIS 10, .NET 8",
    ready: "Ready for Azure",
    sku: "Standard_D4s_v5",
    cost: 142.4,
    storage: 15.36,
    iops: 180,
    cpuPct: 28,
    memPct: 41,
    disksDetail: [{ name: "Hard disk 1", size: 80, rec: "Premium SSD P10" }],
    nics: [{ name: "Network adapter 1", ip: "10.10.20.11", mac: "00:50:56:a1:11:01" }],
    target: true,
  },
  {
    id: "app01",
    name: "APP-01",
    os: "Windows Server 2019 Datacenter",
    power: "Powered On",
    cpu: 4,
    mem: 8,
    disks: "OS 127 GB",
    ip: "10.10.20.21",
    tools: "VMware Tools 12.1 (Running)",
    host: "esxi-prod-01.contoso.local",
    cluster: "Prod-Cluster",
    apps: "IIS, Contoso.Orders API",
    ready: "Ready for Azure",
    sku: "Standard_D4s_v5",
    cost: 142.4,
    storage: 19.56,
    iops: 95,
    cpuPct: 22,
    memPct: 55,
    disksDetail: [{ name: "Hard disk 1", size: 127, rec: "Premium SSD P15" }],
    nics: [{ name: "Network adapter 1", ip: "10.10.20.21", mac: "00:50:56:a1:11:02" }],
    target: false,
  },
  {
    id: "sql01",
    name: "SQL-01",
    os: "Windows Server 2022 + SQL Server 2022",
    power: "Powered On",
    cpu: 8,
    mem: 32,
    disks: "OS 256 GB + Data 500 GB",
    ip: "10.10.20.31",
    tools: "VMware Tools 12.3 (Running)",
    host: "esxi-prod-02.contoso.local",
    cluster: "Prod-Cluster",
    apps: "SQL Server 2022 (MSSQLSERVER)",
    ready: "Ready with conditions",
    sku: "Standard_E8s_v5",
    cost: 486.2,
    storage: 112.8,
    iops: 1400,
    cpuPct: 47,
    memPct: 68,
    disksDetail: [
      { name: "Hard disk 1", size: 256, rec: "Premium SSD P20" },
      { name: "Hard disk 2", size: 500, rec: "Premium SSD P30" },
    ],
    nics: [{ name: "Network adapter 1", ip: "10.10.20.31", mac: "00:50:56:a1:11:03" }],
    target: false,
  },
  {
    id: "lnx01",
    name: "LINUX-WEB-01",
    os: "Ubuntu 22.04 LTS",
    power: "Powered On",
    cpu: 2,
    mem: 4,
    disks: "OS 64 GB",
    ip: "10.10.20.41",
    tools: "open-vm-tools 12.1",
    host: "esxi-prod-02.contoso.local",
    cluster: "Prod-Cluster",
    apps: "nginx 1.24, Node.js 20",
    ready: "Ready for Azure",
    sku: "Standard_B2s",
    cost: 30.37,
    storage: 9.6,
    iops: 40,
    cpuPct: 18,
    memPct: 33,
    disksDetail: [{ name: "Hard disk 1", size: 64, rec: "Standard SSD E6" }],
    nics: [{ name: "Network adapter 1", ip: "10.10.20.41", mac: "00:50:56:a1:11:04" }],
    target: false,
  },
];

const STEPS = [
  {
    id: "signin",
    module: "0 · Access",
    title: "Sign in to Azure",
    short: "Portal authentication",
    url: "https://portal.azure.com",
    sim: "portal",
    objective: "Authenticate to the Contoso Microsoft Entra tenant and open the Azure portal.",
    tasks: [
      { id: "login", text: "Sign in as admin@contoso.com" },
    ],
    hint: "Use the lab credentials from the briefing card. Username is admin@contoso.com and the password is Contoso@Azure2026.",
  },
  {
    id: "create-project",
    module: "1 · Project",
    title: "Create Azure Migrate project",
    short: "Subscription, RG, geography",
    url: "https://portal.azure.com/#view/Microsoft_Azure_Migrate",
    sim: "portal",
    objective: "Create the Azure Migrate project that stores discovery metadata and hosts assessment + migration tools.",
    tasks: [
      { id: "open-migrate", text: "Open Azure Migrate from portal search" },
      { id: "create-rg", text: "Create resource group rg-migrate-prod" },
      { id: "create-proj", text: "Create project contoso-vmware-migrate in Asia" },
    ],
    hint: "Project geography stores metadata only. You can still migrate VMs to East US later. Name and RG must match the lab standard.",
  },
  {
    id: "discover-key",
    module: "2 · Discover",
    title: "Generate project key & download OVA",
    short: "Appliance name + key",
    url: "https://portal.azure.com/#view/Microsoft_Azure_Migrate/Discover",
    sim: "portal",
    objective: "Start VMware discovery, name the appliance, generate the project key, and download the OVA template.",
    tasks: [
      { id: "discover", text: "Start Discover for VMware vSphere (agentless)" },
      { id: "gen-key", text: "Name appliance contosoappl01 and generate the key" },
      { id: "dl-ova", text: "Download the Azure Migrate appliance OVA" },
    ],
    hint: "Appliance name must be alphanumeric and 14 characters or fewer. Use exactly contosoappl01. Do not close the Discover blade while resources are created.",
  },
  {
    id: "vsphere-ova",
    module: "3 · vCenter",
    title: "Deploy appliance on vCenter",
    short: "Deploy OVF wizard",
    url: "https://vcenter.contoso.local/ui",
    sim: "vsphere",
    objective: "Import the OVA into vCenter and deploy the appliance VM on Prod-Cluster with internet-facing networking.",
    tasks: [
      { id: "login-vc", text: "Sign in to vCenter as migrate-svc@vsphere.local" },
      { id: "deploy-ovf", text: "Complete Deploy OVF Template wizard" },
      { id: "power-on", text: "Power on AzureMigrateAppl and note 10.10.1.50" },
    ],
    hint: "Map the VM to VM-Network (management + internet). Thick provision lazy zeroed is acceptable. Do not place the appliance on an isolated lab VLAN.",
  },
  {
    id: "appl-register",
    module: "4 · Appliance",
    title: "Configure and register appliance",
    short: "Config Manager + Entra login",
    url: "https://10.10.1.50:44368",
    sim: "appliance",
    objective: "Run prerequisite checks, paste the project key, auto-update services, sign in to Azure, and install VDDK.",
    tasks: [
      { id: "prereq", text: "Pass connectivity and time-sync checks" },
      { id: "paste-key", text: "Paste the project key and start auto-update" },
      { id: "aad-login", text: "Register the appliance with Azure (device login)" },
      { id: "vddk", text: "Install VMware VDDK 8.0 for agentless replication" },
    ],
    hint: "Open https://10.10.1.50:44368. The key was generated in the portal (starts with CONTOSOAPPL01). VDDK is required for agentless disk reads via CBT snapshots.",
  },
  {
    id: "appl-discover",
    module: "5 · Discovery",
    title: "Connect vCenter and start discovery",
    short: "Credentials + discovery source",
    url: "https://10.10.1.50:44368/#discovery",
    sim: "appliance",
    objective: "Add the vCenter service account, register vcenter.contoso.local, optionally add guest credentials, and start continuous discovery.",
    tasks: [
      { id: "vc-creds", text: "Add vCenter credentials migrate-svc@vsphere.local" },
      { id: "vc-source", text: "Add discovery source vcenter.contoso.local:443" },
      { id: "start-disc", text: "Start continuous discovery" },
    ],
    hint: "The vCenter account needs at least Read-only at datacenter (propagate). Guest Operations are needed for software inventory. Port 443 to vCenter; 902/443 to ESXi for replication later.",
  },
  {
    id: "review-disc",
    module: "6 · Inventory",
    title: "Review discovered servers",
    short: "Portal inventory",
    url: "https://portal.azure.com/#view/Microsoft_Azure_Migrate/Discovered",
    sim: "portal",
    objective: "Confirm the four Contoso VMs are visible in Azure Migrate and inspect WEB-01 properties.",
    tasks: [
      { id: "see-vms", text: "Wait until 4 VMware servers are discovered" },
      { id: "open-web", text: "Open WEB-01 and confirm VMware Tools + disks" },
    ],
    hint: "First inventory usually appears within a few minutes. Performance data used for sizing continues to collect (best after 24 hours in production).",
  },
  {
    id: "assess",
    module: "7 · Assess",
    title: "Create Azure VM assessment",
    short: "Group + performance sizing",
    url: "https://portal.azure.com/#view/Microsoft_Azure_Migrate/Assess",
    sim: "portal",
    objective: "Group the discovered VMs and run a performance-based Azure VM assessment targeting East US.",
    tasks: [
      { id: "new-assess", text: "Create assessment Assess-Contoso-Wave1" },
      { id: "group", text: "Create group Wave1-VMware and include WEB-01" },
      { id: "run", text: "Run the assessment and open the report" },
    ],
    hint: "Use performance-based sizing, target East US, pay-as-you-go, and allow D-series / E-series. WEB-01 must be in the group.",
  },
  {
    id: "replicate",
    module: "8 · Replicate",
    title: "Enable agentless replication",
    short: "WEB-01 → East US",
    url: "https://portal.azure.com/#view/Microsoft_Azure_Migrate/Replicate",
    sim: "portal",
    objective: "Replicate WEB-01 to the landing-zone VNet using the registered appliance. No in-guest agent is installed.",
    tasks: [
      { id: "start-rep", text: "Start Replicate for VMware / agentless" },
      { id: "pick-web", text: "Select WEB-01 and target rg-migrate-prod / East US" },
      { id: "rep-ok", text: "Wait until replication status is Protected (100%)" },
    ],
    hint: "Target VNet: vnet-landing-eus / snet-web. Enable Azure Hybrid Benefit if Contoso has Software Assurance. Initial replication uses a vSphere snapshot + CBT.",
  },
  {
    id: "test-mig",
    module: "9 · Test",
    title: "Run a test migration",
    short: "Isolated VNet validation",
    url: "https://portal.azure.com/#view/Microsoft_Azure_Migrate/TestMigrate",
    sim: "portal",
    objective: "Test-migrate WEB-01 into the isolated test VNet, validate boot/RDP, then clean up the test VM.",
    tasks: [
      { id: "test-start", text: "Start test migration of WEB-01 to vnet-test-eus" },
      { id: "test-validate", text: "Confirm the test VM reached Running" },
      { id: "test-clean", text: "Clean up the test migration" },
    ],
    hint: "Never test-migrate into the production VNet. Test migration does not stop the on-premises VM and does not break ongoing replication.",
  },
  {
    id: "cutover",
    module: "10 · Cutover",
    title: "Planned migration and finalize",
    short: "Shutdown + migrate + stop replication",
    url: "https://portal.azure.com/#view/Microsoft_Azure_Migrate/Migrate",
    sim: "portal",
    objective: "Perform a planned migration with no data loss, verify the Azure VM, stop replication, and complete post-cutover tasks.",
    tasks: [
      { id: "migrate", text: "Migrate WEB-01 with on-premises VM shutdown (planned)" },
      { id: "verify", text: "Verify WEB-01 is Running in Azure with a private IP" },
      { id: "stop-rep", text: "Stop replication and mark migration complete" },
    ],
    hint: "Choose Yes to shut down the on-premises VM so the last delta is replicated. After cutover, install the Azure VM agent if needed, update DNS, and decommission the source on a later change window.",
  },
  {
    id: "quiz",
    module: "11 · Check",
    title: "Knowledge check",
    short: "Validate understanding",
    url: "lab://knowledge-check",
    sim: "quiz",
    objective: "Answer the knowledge check. You need 70% to complete the lab.",
    tasks: [{ id: "quiz-pass", text: "Score at least 70% on the knowledge check" }],
    hint: "Questions cover appliance registration, ports, agentless CBT, assessment types, and planned vs test migration.",
  },
  {
    id: "complete",
    module: "Done",
    title: "Lab complete",
    short: "Score and recap",
    url: "lab://complete",
    sim: "complete",
    objective: "Review your score, downloaded artifacts, and the production checklist.",
    tasks: [{ id: "done", text: "Review completion summary" }],
    hint: "Export the lab recap for your evidence folder.",
  },
];

const QUIZ = [
  {
    q: "What does the Azure Migrate project geography control?",
    options: [
      "The only Azure region you are allowed to migrate VMs into",
      "Where discovery/assessment metadata is stored — you can still migrate to another region",
      "The region of the on-premises vCenter Server",
      "The Azure AD tenant location",
    ],
    a: 1,
  },
  {
    q: "An Azure Migrate appliance name must be:",
    options: [
      "Any string up to 64 characters",
      "A valid Azure resource ID",
      "Alphanumeric and 14 characters or fewer",
      "Identical to the vCenter FQDN",
    ],
    a: 2,
  },
  {
    q: "Which port must be open from the appliance to vCenter for discovery?",
    options: ["TCP 902", "TCP 3389", "TCP 443", "UDP 53 only"],
    a: 2,
  },
  {
    q: "Why is VDDK installed on the appliance for this lab?",
    options: [
      "To enable RDP to Windows VMs",
      "To let agentless replication read VM disks via vSphere snapshots / CBT",
      "To convert VMDK to VHDX on the source ESXi host",
      "To register the appliance in Microsoft Entra ID",
    ],
    a: 1,
  },
  {
    q: "Agentless VMware migration installs the Mobility service inside each guest OS.",
    options: ["True", "False"],
    a: 1,
  },
  {
    q: "A performance-based assessment sizes Azure VMs using:",
    options: [
      "Only the configured on-premises vCPU and RAM",
      "Collected CPU, memory, IOPS and throughput utilization",
      "The last vCenter snapshot size",
      "Azure Advisor recommendations from another subscription",
    ],
    a: 1,
  },
  {
    q: "What is the correct use of a test migration?",
    options: [
      "Cut production traffic over and retire the source VM",
      "Boot a copy in an isolated VNet to validate without stopping the source",
      "Replace assessment as the only readiness check",
      "Install the Mobility agent on WEB-01",
    ],
    a: 1,
  },
  {
    q: "For a planned migration with no data loss you should:",
    options: [
      "Leave the source VM running and delete its disks",
      "Shut down the source VM so the last delta can replicate, then cut over",
      "Power off the Azure Migrate appliance first",
      "Disable CBT on the VM",
    ],
    a: 1,
  },
  {
    q: "A single VMware Azure Migrate appliance can typically discover up to how many servers?",
    options: ["100", "1,000", "10,000", "Unlimited"],
    a: 2,
  },
  {
    q: "Which vCenter role is the minimum for discovery/assessment (not replication)?",
    options: [
      "Administrator@vCenter",
      "Read-only (plus Guest Operations if you want software inventory)",
      "No Access with propagate",
      "Datastore Consumer only",
    ],
    a: 1,
  },
];

const PORTS = [
  { from: "Admin workstation", to: "Appliance :44368", why: "Appliance Configuration Manager UI" },
  { from: "Admin workstation", to: "Appliance :3389", why: "RDP to appliance OS if needed" },
  { from: "Appliance", to: "vCenter :443", why: "Discovery, snapshots, orchestration" },
  { from: "Appliance", to: "ESXi :443 / :902", why: "Inventory / NFC disk data for replication" },
  { from: "Appliance", to: "Azure URLs :443", why: "Control plane + replicated data upload" },
];
